### ISSUE TITLE
Connectivity Banner is shown behind BottomAppBar

### ISSUE THREAD

**Issue by nekoto-kun** [Vanethos/flutter_connectivity_widget#11]
Good day!
Your widget is working as expected, but in my case, I'm using bottomNavigationBar with BottomAppBar widget in the Scaffold, the banner is shown and fully animated just behind that navigation bar.
My widget tree is something like this:

```
Scaffold(
  extendBody: true,
  appBar: AppBar(...),
  body: ConnectivityWidget(
    builder: (ctx, isOnline) => PageView(...),
  ),
  bottomNavigationBar: BottomAppBar(...),
  ...
)
```

What should I do?

**Comment by Vanethos** [comment]
Hi @nekoto-kun thank you for filling an issue.

Can you create a minimal working example so that I can run it? I'm currently using it in my project and I don't have the same problem.

**Comment by Vanethos** [comment]
Dismissed as stale
