### ISSUE TITLE
Disable checking if flutter web

### ISSUE THREAD

**Issue by chitgoks** [Vanethos/flutter_connectivity_widget#20]
yes. the lib is not supported in web. but to keep the same code, would it be possible to somehow detect that if it is kIsWeb, then the stream builder will just ignore connections so that the ConnectivityWidget(builder: (context, isOnline) { }) will still be embedded in the build widget even if it is deployed for flutter web

rather than doing a workaround now to add the widget if it is not web.

**Comment by Vanethos** [comment]
What if we are using this in a Web App that supports offline usage?

**Comment by chitgoks** [comment]
is that for me? sorry whats pwa?

**Comment by Vanethos** [comment]
Progressive Web App

https://web.dev/progressive-web-apps/

As such we can have web apps that have offline functionality
