### ISSUE TITLE
Conection mobile only 4G is not detected

### ISSUE THREAD

**Issue by Liliana99** [Vanethos/flutter_connectivity_widget#21]
Hi,

When I deactivate the Wifi connection , the mobile still is conected with 4g but the plugin says the result is not conected with network.

**Comment by Vanethos** [comment]
Hi @Liliana99 can you give me more information about your device?

Android? iOS? What OS and model?

**Comment by Liliana99** [comment]
Hi,

It works ok,  on both platforms.
Sorry it was bad configuration for me !!

**Comment by Vanethos** [comment]
Awesome!

Going to close it now
