### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ch3ckmat3** [Vanethos/flutter_connectivity_widget#3]
I just tried the example on my handset and it is not detecting the online status correctly. It is always offline. I tried changing the custom ping server URL, and also commenting the custom server out, but with no luck.

Can you please check the code for bugs etc.?

**Comment by Vanethos** [comment]
Will do asap, sorry for the delay! And I've seen also #2 and will work on that

**Comment by Vanethos** [comment]
Please check with version 0.1.2 if this is the case
