### ISSUE TITLE
connectivity_widget  not use nullsafety

### ISSUE THREAD

**Issue by s2yed** [Vanethos/flutter_connectivity_widget#30]
And because flutter_cache_manager >=3.0.0-nullsafety.0 depends on http ^0.13.0 and connectivity_widget >=0.1.6 depends on rxdart ^0.24.0, if flutter_cache_manager >=3.0.0-nullsafety.0 and connectivity_widget any then dio ^2.1.0 or rxdart ^0.24.0.

**Comment by s2yed** [comment]
help

**Comment by Vanethos** [comment]
Fixed on latest version, please try adjusting your dependencies constraints
