### ISSUE TITLE
flutter pub get Resolving dependencies error

### ISSUE THREAD

**Issue by Veeramani-Schnell** [Vanethos/flutter_connectivity_widget#35]
Because connectivity_widget >=1.0.0 depends on http ^0.13.5 and google_fonts 6.1.0 depends on http ^1.0.0, connectivity_widget >=1.0.0 is incompatible with google_fonts 6.1.0.
And because no versions of google_fonts match >6.1.0 <7.0.0, connectivity_widget >=1.0.0 is incompatible with google_fonts ^6.1.0.
So, because <app_label> depends on both google_fonts ^6.1.0 and connectivity_widget ^1.2.0, version solving failed.
exit code 1

Note:
I have using connectivity_widget: ^1.2.0 and not used http package instead of i have  using Dio

**Comment by Vanethos** [comment]
This will be addressed in a later update, where I will bump the `http` dependency to 1.0.0

**Comment by Vanethos** [comment]
Solved with version 2.0.0
