### ISSUE TITLE
DIO dependency outdated

### ISSUE THREAD

**Issue by alvinvin00** [Vanethos/flutter_connectivity_widget#7]
I use DIO version 3 inside my project but the package depends on DIO v2.x.x so i can't use this package with DIO v3 installed

**Comment by alvinvin00** [comment]
P.S. I read the v1.2 changelog (stated that DIO was removed), but DIO package dependencies are still there

**Comment by pravinarr** [comment]
The reason for this issue is that, the changes are not properly merged to master branch. @alvinvin00 you can directly reference this git commit on feature/example branch in your pubspec.yaml if you really want to use it.

**Comment by Vanethos** [comment]
You are both right!

I have now corrected this, sorry for the inconvenience.

Please try version 0.1.3

**Comment by pravinarr** [comment]
@Vanethos I could not find the version 0.1.3 , can you recheck?

**Comment by e200** [comment]
Same here. There's no v.0.1.3 yet?

**Comment by thiagotalma** [comment]
@Vanethos any news here?

**Comment by Vanethos** [comment]
Sorry, I published last time but didn't check that it encountered an error.

Basically I'm using a fork of `connectivity` since, at the time, this package required a Location request in the Info.plist file.

When publishing it into pub.dev, I get now the following error:

`Package dependency connectivity is a git dependency, this not allowed in published packages.`

I will have to publish the forked package if I want to have this package with no location permission request.

Deeply sorry for being unresponsive

**Comment by Vanethos** [comment]
Created package https://pub.dev/packages/simple_connectivity for this issue

Released version v0.1.4 in https://pub.dev/packages/connectivity_widget

**Comment by yemistar** [comment]
When I add your package to my pubspec.yaml, I get this error. Do you have any Ideas why this might be happening? Thanks. (I am trying to run it on an iphone) 

```
Xcode's output:
↳
    /Users/yemi/.pub-cache/hosted/pub.dartlang.org/simple_connectivity-0.1.0/ios/Classes/ConnectivityPlugin.m:27:35: warning: incompatible pointer types sending 'FLTConnectivityPlugin *' to parameter of type 'NSObject<FlutterStreamHandler> * _Nullable' [-Wincompatible-pointer-types]
      [streamChannel setStreamHandler:instance];
                                      ^~~~~~~~
    In module 'Flutter' imported from /Users/yemi/.pub-cache/hosted/pub.dartlang.org/simple_connectivity-0.1.0/ios/Classes/ConnectivityPlugin.h:5:
    /Users/yemi/Desktop/Rocking-W-app/frontend/ios/Pods/../Flutter/Flutter.framework/Headers/FlutterChannels.h:382:69: note: passing argument to parameter 'handler' here
    - (void)setStreamHandler:(NSObject<FlutterStreamHandler>* _Nullable)handler;
                                                                        ^
    1 warning generated.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/yemi/Desktop/Rocking-W-app/frontend/ios/Runner/GeneratedPluginRegistrant.m:22:9: fatal error: module 'simple_connectivity' not found
    @import simple_connectivity;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by Vanethos** [comment]
@yemistar is it possible to open a new issue? And what version are you using?
